name:                arya
version:             0.1.0.0
github:              "jfaure/arya"
license:             BSD3
author:              "James Faure"
maintainer:          "james.faure@epitech.eu"
copyright:           "2019 James Faure"

extra-source-files:
- README.md

synopsis:            Array oriented calculus of inductive constructions
category:            Compilers

description:         Please see the README on GitHub at <https://github.com/jfaure/arya#readme>

dependencies:
- base >= 4.7 && < 5
- filepath
- directory
- llvm-hs-pure >= 9.0.0
- llvm-hs >= 9.0.0
- llvm-hs-pretty
- parser-combinators
- megaparsec > 7.0
- transformers
- vector
- haskeline
- optparse-applicative
- text
- bytestring
- containers
- unordered-containers
- mtl

  # library:
  #   source-dirs:

executables:
  arya-exe:
    source-dirs:
    - compiler/
    - compiler/1_Main/
    - compiler/2_Parse/
    - compiler/3_Core/
    - compiler/3__parse2core/
    - compiler/4_LFVM-STG/
    - compiler/conv

    main:          Main.hs
    ghc-options:  -threaded -dynamic -fdefer-typed-holes -Wno-typed-holes #-Wunused-imports -Wunused-binds
    default-extensions:
    - LambdaCase
    - EmptyCase
    - ViewPatterns
    - StandaloneDeriving
    - MultiWayIf
    - PartialTypeSignatures
    - ScopedTypeVariables
    - RankNTypes
    - FlexibleContexts
    - TupleSections
    - ConstraintKinds
    - RecursiveDo
#   - PolyKinds
#   - GADTs -- Parser.hs crashes ghc with this
#   - DataKinds
   #    dependencies: arya

#tests:
#  arya-test:
#    main:                Spec.hs
#    source-dirs:         test
#    ghc-options: -threaded
#    #   dependencies: arya
