name:                arya
version:             0.1.0.0
github:              "jfaure/arya"
license:             BSD3
author:              "James Faure"
maintainer:          "james.faure@epitech.eu"
copyright:           "2019 James Faure"

extra-source-files:
- README.md

synopsis:            Array oriented calculus of inductive constructions
category:            Compilers

description:         Please see the README on GitHub at <https://github.com/jfaure/arya#readme>

dependencies:
- primitive
- base >= 4.7 && < 5
- hashable
- text
- vector
- containers
- lens
- parser-combinators
- megaparsec > 7.0
- transformers
- optparse-applicative
- bytestring
- mtl
- unordered-containers
- filepath
- directory
- haskeline
- llvm-hs-pure >= 9.0.0
- llvm-hs >= 9.0.0
- llvm-hs-pretty

default-extensions:
- LambdaCase
- EmptyCase
- ViewPatterns
- StandaloneDeriving
- MultiWayIf
- PartialTypeSignatures
- ScopedTypeVariables
- RankNTypes
- FlexibleContexts
- TupleSections
- ConstraintKinds
- RecursiveDo
- OverloadedStrings
# - GADTs
# - PolyKinds
# - DataKinds

library:
  source-dirs:
    - compiler/
    - compiler/3_Core/
    - compiler/2_Parse/
    - compiler/4_LFVM-STG/

ghc-options:  -dynamic -fdefer-typed-holes -Wno-typed-holes #-Wunused-imports -Wunused-binds -threaded
executables:
  arya-exe:
    dependencies: arya
    source-dirs:
    - compiler/1_Main/
    main:          Main.hs
    ghc-options:  -dynamic -fdefer-typed-holes -Wno-typed-holes #-Wunused-imports -Wunused-binds -threaded

#tests:
#  arya-test:
#    main:                Spec.hs
#    source-dirs:         test
#    ghc-options: -threaded
#    #   dependencies: arya
